package Presentacion;

import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;

import javax.swing.JOptionPane;

import Datos.cls_clientes;
import Datos.cls_pedido;
import Negocio.cls_validar_cliente;
import Negocio.cls_validar_pedido;

public class frm_restaurante extends javax.swing.JFrame {

    LinkedList<cls_clientes> clientes = new LinkedList<cls_clientes>();
    LinkedList<cls_pedido> pedidos = new LinkedList<>();//Lista de pedidos
    cls_validar_cliente objValidar = new cls_validar_cliente();
    cls_validar_pedido objValidar2 = new cls_validar_pedido();//Instancia unica
    boolean sw;
    int activo = 0;
    int posicion;

    public frm_restaurante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_contacto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_correo = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btn_nuevo = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        btn_consultar = new javax.swing.JButton();
        btn_cambiarEstado = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txt_id1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btn_nuevoPedido = new javax.swing.JButton();
        btn_guardarPedido = new javax.swing.JButton();
        btn_consultarCliente = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txt_nombre1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_detalleOrden = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_totalPagar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(27, 67, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Formulario de registro de pedidos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jTabbedPane1.setBackground(new java.awt.Color(64, 145, 108));

        jPanel2.setBackground(new java.awt.Color(149, 213, 178));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Identificacion:");

        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Contacto:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Correo:");

        jPanel4.setBackground(new java.awt.Color(82, 183, 136));

        btn_nuevo.setText("Nuevo");
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_consultar.setText("Consultar");
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarActionPerformed(evt);
            }
        });

        btn_cambiarEstado.setText("Cambiar Estado");
        btn_cambiarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cambiarEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_cambiarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btn_nuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_guardar)
                .addGap(18, 18, 18)
                .addComponent(btn_consultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_cambiarEstado)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_nombre)
                    .addComponent(txt_contacto)
                    .addComponent(txt_correo, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                    .addComponent(txt_id))
                .addGap(12, 12, 12)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Clientes", jPanel2);

        jPanel3.setBackground(new java.awt.Color(149, 213, 178));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Identificacion:");

        txt_id1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id1ActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(82, 183, 136));

        btn_nuevoPedido.setText("Nuevo pedido");
        btn_nuevoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoPedidoActionPerformed(evt);
            }
        });

        btn_guardarPedido.setText("Guardar pedido");
        btn_guardarPedido.setActionCommand("Guardar pedido");
        btn_guardarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarPedidoActionPerformed(evt);
            }
        });

        btn_consultarCliente.setText("Consultar cliente");
        btn_consultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_nuevoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_consultarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_guardarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btn_nuevoPedido)
                .addGap(18, 18, 18)
                .addComponent(btn_guardarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_consultarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Nombre");

        txt_nombre1.setEditable(false);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Total a pagar:");

        txt_detalleOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_detalleOrdenActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Detalle Orden:");

        txt_totalPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalPagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_detalleOrden, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                    .addComponent(txt_totalPagar)
                    .addComponent(txt_id1)
                    .addComponent(txt_nombre1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_id1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txt_detalleOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_totalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Pedidos", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected void txt_detalleOrdenActionPerformed(ActionEvent evt) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'txt_detalleOrdenActionPerformed'");
    }

    private void txt_totalPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalPagarActionPerformed

    private void txt_id1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txt_id1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txt_id1ActionPerformed

    private void fnt_nuevopedido() {
        txt_id1.setEnabled(true);
        txt_id1.setText("");
        txt_nombre1.setText("");
        txt_detalleOrden.setText("");
        txt_totalPagar.setText("");
        txt_id1.requestFocus();
        btn_guardarPedido.setEnabled(false);
    }

    private void btn_nuevoPedidoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_nuevoPedidoActionPerformed
        fnt_nuevopedido();
    }// GEN-LAST:event_btn_nuevoPedidoActionPerformed

    private void fnt_guardar_pedido() {
        fnt_consultar(txt_id1.getText(), "4");
        if (activo == 0) {
            JOptionPane.showMessageDialog(null, "Error, el cliente se encuentra inactivo");
        }
        if (activo == 1) {
            List<String> errores = new ArrayList<>();
            if (fnt_validaridentidicacion(txt_id.getText()) == false) {
                errores.add("Identificacion");
            }
            if (fnt_validardetalle(txt_detalleOrden.getText()) == false) {
                errores.add("Detalle");
            }
            if (fnt_validar_totalPagar(txt_totalPagar.getText()) == false) {
                errores.add("Total a Pagar");
            }

            if (errores.isEmpty() == false) {
                String mensajeError = "Se encontraron errores:\n" + String.join("\n", errores);
                JOptionPane.showMessageDialog(null, mensajeError);
                return;
            }
            objValidar2.validarDatosEntrada(txt_id1.getText(), txt_detalleOrden.getText(), txt_totalPagar.getText());

            clientes.add(new cls_clientes(txt_id.getText(), txt_nombre.getText(), txt_contacto.getText(),
                    txt_correo.getText()));

            JOptionPane.showMessageDialog(null, objValidar2.getMsn());
        }

    }

    private void btn_guardarPedidoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_guardarPedidoActionPerformed
        fnt_guardar_pedido();
    }// GEN-LAST:event_btn_guardarPedidoActionPerformed

    private static boolean fnt_validardetalle(String detorden) {
        return detorden.matches("^([A-Za-z,.\\s]+)$");
    }

    private static boolean fnt_validar_totalPagar(String total) {
        return total.matches("[0-9]+$");
    }

    private void btn_consultarClienteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_consultarClienteActionPerformed
        fnt_consultar(txt_id1.getText(), "3");
    }// GEN-LAST:event_btn_consultarClienteActionPerformed

    private void txt_id2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txt_id2ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txt_id2ActionPerformed

    private void fnt_consultar(String id, String tipo) {
        sw = false;
        posicion = 0;
        for (int i = 0; i < clientes.size(); i++) {
            if (id.equals(clientes.get(i).getIdStr())) {
                sw = true;
                posicion = i;
                break;
            }

        }
        if (sw == false) {
            if (!tipo.equals("4")) {
                JOptionPane.showMessageDialog(null, "No se encontraron datos");
            }

            if (tipo.equals("3")) {
                txt_nombre1.setText("");
            }

        } else {
            if (tipo.equals("1")) {
                txt_contacto.setText(clientes.get(posicion).getContactoStr());
                txt_correo.setText(clientes.get(posicion).getCorreoStr());
                txt_nombre.setText(clientes.get(posicion).getNombreStr());
            }
            if (tipo.equals("2")) {
                clientes.get(posicion).setEstado(1);
                JOptionPane.showMessageDialog(null, "Estado actualizado");
            }
            if (tipo.equals("3")) {
                txt_id1.setEnabled(false);
                btn_guardarPedido.setEnabled(true);
                txt_nombre1.setText(clientes.get(posicion).getNombreStr());
            }
            if (tipo.equals("4")) {
                activo = clientes.get(posicion).getEstado();

            }
        }

    }

    private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_consultarActionPerformed
        fnt_consultar(txt_id.getText(), "1");
    }// GEN-LAST:event_btn_consultarActionPerformed

    private void btn_cambiarEstadoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_cambiarEstadoActionPerformed
        fnt_consultar(txt_id.getText(), "2");
        JOptionPane.showMessageDialog(null, clientes.get(posicion).getEstado());
    }// GEN-LAST:event_btn_cambiarEstadoActionPerformed

    private void fnt_guardarCliente() {

        List<String> errores = new ArrayList<>();
        if (fnt_validaridentidicacion(txt_id.getText()) == false) {
            errores.add("Identificacion");
        }
        if (fnt_validarnombre(txt_nombre.getText()) == false) {
            errores.add("nombre");
        }
        if (fnt_validarcontacto(txt_contacto.getText()) == false) {
            errores.add("Contacto");
        }
        if (fnt_validarcorreo(txt_correo.getText()) == false) {
            errores.add("Correo");
        }

        if (errores.isEmpty() == false) {
            String mensajeError = "Se encontraron errores:\n" + String.join("\n", errores);
            JOptionPane.showMessageDialog(null, mensajeError);
            return;
        }

        objValidar.validarDatosEntrada(txt_id.getText(), txt_nombre.getText(), txt_contacto.getText(),
                txt_correo.getText());

        clientes.add(new cls_clientes(txt_id.getText(), txt_nombre.getText(), txt_contacto.getText(),
                txt_correo.getText()));

        JOptionPane.showMessageDialog(null, objValidar.getmsn());
    }

    private static boolean fnt_validarnombre(String nombre) {
        return nombre.matches("^([A-Z]+[ ]?){1,20}$");
    }

    private static boolean fnt_validaridentidicacion(String numero) {
        return numero.matches("[0-9]{10}");
    }

    private static boolean fnt_validarcontacto(String contacto) {
        return contacto.matches("[0-9]{10}");
    }

    private static boolean fnt_validarcorreo(String correo) {
        return correo.matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$");
    }

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_guardarActionPerformed
        fnt_guardarCliente();
    }// GEN-LAST:event_btn_guardarActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txt_idActionPerformed

    private void fnt_nuevo_cliente() {
        txt_contacto.setText("");
        txt_nombre.setText("");
        txt_correo.setText("");
        txt_id.setText("");
        txt_id.requestFocus();
    }

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_nuevoActionPerformed
        fnt_nuevo_cliente();
    }// GEN-LAST:event_btn_nuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_restaurante.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_restaurante.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_restaurante.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_restaurante.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_restaurante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cambiarEstado;
    private javax.swing.JButton btn_consultar;
    private javax.swing.JButton btn_consultarCliente;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_guardarPedido;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JButton btn_nuevoPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txt_contacto;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_detalleOrden;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_id1;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_nombre1;
    private javax.swing.JTextField txt_totalPagar;
    // End of variables declaration//GEN-END:variables
}
